# Generated by Django 4.2.9 on 2024-03-11 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('intransit', 'intransit'), ('dispatched', 'dispatched'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order-placed', max_length=200)),
                ('Bike_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
