# Generated by Django 4.2.9 on 2024-04-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Bike_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bike.bike'),
        ),
    ]
