# Generated by Django 4.2.9 on 2024-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_bike_is_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cod', 'cod'), ('online', 'online')], default='cod', max_length=200),
        ),
    ]
