# Generated by Django 4.2.9 on 2024-05-07 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0007_alter_service_owner_alter_wishlist_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to=settings.AUTH_USER_MODEL),
        ),
    ]
